<<<<<<< HEAD
# Generated by Django 3.0.6 on 2020-05-27 23:20
=======
# Generated by Django 3.0.6 on 2020-05-27 20:31
>>>>>>> 7a3f3b372e6c30bfb5be3feb2c735d3de519caf8

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
<<<<<<< HEAD
                ('image', models.ImageField(default='default.jpg', upload_to='profile_pictures')),
=======
                ('image', models.ImageField(default='default.jpg', upload_to='profile_pics')),
>>>>>>> 7a3f3b372e6c30bfb5be3feb2c735d3de519caf8
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
