# Generated by Django 3.0.6 on 2020-06-03 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_likedrecipes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LikedRecipes',
        ),
    ]
