# Generated by Django 3.0.6 on 2020-05-11 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipes',
            name='author',
        ),
        migrations.RemoveField(
            model_name='recipes',
            name='title',
        ),
    ]
