# Generated by Django 3.0.6 on 2020-05-27 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
